// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()

        maven {
            url  "https://phonepe.mycloudrepo.io/public/repositories/phonepe-intentsdk-android"
        }
    }
    dependencies {
        classpath libs.google.services
        classpath libs.gradle
        classpath libs.kotlin.gradle.plugin
        classpath libs.google.services.v440
    }
}

plugins {
alias(libs.plugins.android.application) apply false
    alias(libs.plugins.jetbrains.kotlin.android) apply false
    id 'com.google.gms.google-services' version '4.4.2' apply false
}
